volumes:
  volume_redis: {}
  volume_thumbor: {}
  volume_sqld: {}

networks:
  iivineri_network:
    driver: bridge

services:
  redis:
    image: redis:8-alpine
    networks:
      - iivineri_network
    ports:
      - ${VIRTUAL_IP}:6379:6379
    volumes:
      - "volume_redis:/data"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  thumbor:
    image: ghcr.io/minimalcompact/thumbor:7.7.4
    ports:
      - ${VIRTUAL_IP}:8000:80
    environment:
      LOG_LEVEL: "DEBUG"
      MAX_WIDTH: 0
      MAX_HEIGHT: 0
      UPLOAD_MAX_SIZE: 0
      SECURITY_KEY: "${THUMBOR_KEY}"
      UPLOAD_ENABLED: "True"
      ALLOW_UNSAFE_URL: "False"
      LOADER: "thumbor.loaders.file_loader"
      FILE_LOADER_ROOT_PATH: "/data/storage"
      STORAGE_EXPIRATION_SECONDS: 3155760000
      UPLOAD_DEFAULT_FILENAME: "image"
    networks:
      - iivineri_network
    volumes:
      - volume_thumbor:/data
    command: ["thumbor"]

  sqld:
    image: ghcr.io/tursodatabase/libsql-server:e4beaca
    networks:
      - iivineri_network
    ports:
      - ${VIRTUAL_IP}:8080:8080
    volumes:
      - "volume_sqld:/var/lib/sqld"
    environment:
      SQLD_NODE: "primary"
      SQLD_AUTH_JWT_KEY: "${SQLD_AUTH_JWT_KEY}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  dbadmin:
    image: coleifer/sqlite-web:latest
    ports:
      - ${VIRTUAL_IP}:8081:8080
    volumes:
      - "volume_sqld:/data:ro"
    entrypoint: sqlite_web
    command: ["/data/iku.db/dbs/default/data", "--host", "0.0.0.0"]
