volumes:
  volume_redis: {}
  volume_rustfs: {}
  volume_sqld: {}

networks:
  iivineri_network:
    driver: bridge

services:
  redis:
    image: redis:8-alpine
    networks:
      - iivineri_network
    ports:
      - ${VIRTUAL_IP}:6379:6379
    volumes:
      - "volume_redis:/data"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  rustfs:
    image: rustfs/rustfs:latest
    networks:
      - iivineri_network
    ports:
      - ${VIRTUAL_IP}:9000:9000
      - ${VIRTUAL_IP}:9001:9001
    volumes:
      - "volume_rustfs:/data"
    environment:
      RUSTFS_VOLUMES: "/data/rustfs0"
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_ACCESS_KEY: "${RUSTFS_ACCESS_KEY}"
      RUSTFS_SECRET_KEY: "${RUSTFS_SECRET_KEY}"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  thumbor:
    image: ghcr.io/minimalcompact/thumbor:7.7.4
    ports:
      - ${VIRTUAL_IP}:8000:80
    depends_on:
      - rustfs
    environment:
      LOG_LEVEL: "DEBUG"
      MAX_WIDTH: 0
      MAX_HEIGHT: 0
      SECURITY_KEY: "${THUMBOR_KEY}"
      UPLOAD_ENABLED: "False"
      ALLOW_UNSAFE_URL: "False"
      LOADER: "tc_aws.loaders.s3_loader"
      TC_AWS_REGION: "us-east-1"
      TC_AWS_ENDPOINT: "http://rustfs:9000"
      TC_AWS_LOADER_BUCKET: "${RUSTFS_BUCKET}"
      AWS_ACCESS_KEY_ID: "${RUSTFS_ACCESS_KEY}"
      AWS_SECRET_ACCESS_KEY: "${RUSTFS_SECRET_KEY}"
      STORAGE_EXPIRATION_SECONDS: 3155760000
    networks:
      - iivineri_network
    command: ["thumbor"]

  sqld:
    image: ghcr.io/tursodatabase/libsql-server:e4beaca
    networks:
      - iivineri_network
    ports:
      - ${VIRTUAL_IP}:8080:8080
    volumes:
      - "volume_sqld:/var/lib/sqld"
    environment:
      SQLD_NODE: "primary"
      SQLD_AUTH_JWT_KEY: "${SQLD_AUTH_JWT_KEY}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  dbadmin:
    image: coleifer/sqlite-web:latest
    ports:
      - ${VIRTUAL_IP}:8081:8080
    volumes:
      - "volume_sqld:/data:ro"
    entrypoint: sqlite_web
    command: ["/data/iku.db/dbs/default/data", "--host", "0.0.0.0"]
