name: Develop Docker Image CI / CD
on:
  push:
    branches: ["develop"]
jobs:
  build-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Webhook
        run: echo 'build-api-ok'

  deploy-api:
    needs: build-api
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: acayseth
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build \
            --file .docker/nest/Dockerfile \
            --tag ghcr.io/acayseth/iivineri:api-develop \
            --push \
            .

  build-web:
    needs: deploy-api
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: acayseth
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build \
            --file .docker/next/Dockerfile \
            --tag ghcr.io/acayseth/iivineri:web-develop \
            --build-arg NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }} \
            --push \
            .
  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Webhook
        run: |
          curl -XPOST 'https://webhook.hellnet.eu/restart-pod?namespace=default&pod_name_pattern=iivineri-dev' --header 'Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}'
