name: WebDev Docker Image CI / CD
on:
  push:
    branches: [ "develop" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx build . \
          --file .docker/next/Dockerfile \
          --tag ghcr.io/acayseth/iivineri:api-develop \
          --build-arg NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }}
      - name: Push the Docker image
        run: docker login ghcr.io -u acayseth -p ${{ secrets.TOKEN }} && docker push ghcr.io/acayseth/iivineri:api-develop
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Webhook
        run: |
          curl -XPOST 'https://webhook.hellnet.eu/restart-pod?namespace=default&pod_name_pattern=iivineri-dev' --header 'Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}'