name: Docker Image CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
    - name: Build the Docker image
      run: |
          echo "NEXT_PUBLIC_PROJECT_URL=${{ secrets.NEXT_PUBLIC_PROJECT_URL }}" >> .env 
          echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}" >> .env 
          echo "GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }}" >> .env 
          echo "GIPHY_RATING=${{ secrets.GIPHY_RATING }}" >> .env 
          echo "GIPHY_TAG_IS_FRIDAY=${{ secrets.GIPHY_TAG_IS_FRIDAY }}" >> .env
          echo "GIPHY_TAG_IS_NOT_FRIDAY=${{ secrets.GIPHY_TAG_IS_NOT_FRIDAY }}" >> .env 
          docker build . --file Dockerfile --tag ghcr.io/acayseth/iivineri:latest
          curl -XPOST 'https://webhook.hellnet.eu/webhook/restart-pod?namespace=default&pod_name_pattern=iivineri' --header 'Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}'
    - name: Push the Docker image
      run: docker login ghcr.io -u acayseth -p ${{ secrets.TOKEN }} && docker push ghcr.io/acayseth/iivineri:latest

