name: Develop Docker Image CI / CD
on:
  push:
    branches: [ "develop" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: acayseth
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file .docker/nest/Dockerfile \
            --tag ghcr.io/acayseth/iivineri:web-develop \
            --build-arg NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }} \
            --push \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Webhook
        run: |
          curl -XPOST 'https://webhook.hellnet.eu/restart-pod?namespace=default&pod_name_pattern=iivineri-dev' --header 'Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}'